# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestions',
            name='answer_query',
            field=models.CharField(default='change this', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonquestions',
            name='hint',
            field=models.CharField(default='change this', max_length=2000),
            preserve_default=False,
        ),
    ]
