# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('years_exp', models.IntegerField()),
                ('num_of_specials', models.IntegerField()),
            ],
        ),
    ]
