# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0002_auto_20160330_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rapper', models.CharField(max_length=100)),
                ('copies_sold_first_week', models.IntegerField()),
                ('quality_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('top_spender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('records_dropped', models.IntegerField()),
                ('rap_battles_won', models.IntegerField()),
                ('money_spent_on_strippers_2015', models.IntegerField()),
                ('gold_chains_owned', models.IntegerField()),
            ],
        ),
    ]
