# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0003_lessonquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestions',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
