# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querytool', '0004_lessonquestions_question_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('balcony', models.BooleanField()),
            ],
        ),
    ]
